# -*- coding: utf-8 -*-
"""First_Come_First_Serve.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_-k6sEoiGOp4bfu2SYw6PlmXO0MnuI9O

**First Come First Serve**
"""

print("Enter the No. of Process->",end=" ")
p = int(input()) 
print('Enter the task name->', end=" ")
task = input().split()
print('Enter the No. of task time->', end=" ")
time = list(map(int, input().split()))

task

time

import pandas as pd
l = [task,time]
df = pd.DataFrame(l).transpose()
df.columns = ["Task","Time"]
df

# Gantt Chart
print(0,end=' ')
tmp = 0
l2 = [0]
for tsk, tm in zip(df.Task,df.Time): 
    tmp+=tm
    l2.append(tmp)
    print(tsk,tmp,end=' ')

l2 = l2[:-1]
import numpy as np
w = np.sum(l2)
print('Total waiting time : {0:.2f}ms'.format(w))

l2 = l2[:-1]
import numpy as np
w = np.sum(l2)/len(l2)
print('Average waiting time : {0:.2f}ms'.format(w))

import pandas as pd
l3 = [l2,time]
df1 = pd.DataFrame(l3).transpose()
df1.columns = ["Wait","Time"]
df1

print(0,end=' ')
tmp2 = 0
l4 = [0]
for i,j in zip(df1.Wait,df1.Time): 
    tmp2+=j
    l4.append(tmp2)
    print(i,tmp2,end=' ')

l4 = l4[:-1]
import numpy as np
Turn = np.sum(l4)
print('Total Trun around  time : {0:.2f}ms'.format(Turn))

l4 = l4[:-1]
import numpy as np
Turn = np.sum(l4)/len(l4)
print('Average Trun around  time : {0:.2f}ms'.format(Turn))